### ISSUE TITLE
Getting this error on Maven: Could not find artifact co.uzzu.dotenv:gradle:jar:1.0.1 in central (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by maranza** [uzzu/dotenv-gradle#13]

**Comment by uzzu** [comment]
@maranza 
Sorry for late reply.
This gradle plugin is available at Gradle Plugin Portal, it's not Maven Central.
Please add `gradlePluginPortal()` into your buildscript repositories section.

https://docs.gradle.org/current/userguide/plugins.html

**Comment by uzzu** [comment]
https://github.com/uzzu/dotenv-gradle/issues/13#issuecomment-914137737 If this doesn't help, please reopen it.
I'll add a note to the README that this plugin is available on the Gradle Plugin Portal.
