### ISSUE TITLE
Can i change file name?

### ISSUE THREAD

**Issue by kamlesh62** [uzzu/dotenv-gradle#14]
I have multiple env files .env .env.staging and so on

**Comment by uzzu** [comment]
This is currently not, but I think it's possible to add the feature.

One limitation is Gradle has no concept of staging, test, production, or local environments, so it is difficult to automatically load one of the .env files. (like next.js)

If you simply want to use a different file name, I will try to implement that.

**Comment by kamlesh62** [comment]
Currently how i do it in my nodejs project is i pickup filename from environement variables
So i just set env files name before building

set ENVFILE=.env.staging && run node server
set ENVFILE=.env.production && npm command

**Comment by uzzu** [comment]
Thanks for giving your use case! 😄 

Changing `.env` file feature was released at 1.2.0.
- Example: https://github.com/uzzu/dotenv-gradle/tree/1.2.0/examples/change_file
- Changelog: https://github.com/uzzu/dotenv-gradle/blob/1.2.0/CHANGELOG.md#120---2021-09-24 

If you have problems using it, please create new issue.
