### ISSUE TITLE
Use as environment

### ISSUE THREAD

**Issue by mindhaq** [uzzu/dotenv-gradle#3]
I would like to use the `env` created by the plugin as an `environment` inside the gradle script, which is a `Map<String,?>`.

Currently, I don't see a way to do that.

**Comment by uzzu** [comment]
@mindhaq Sorry for the rate reply.

Which one do you mean that is like a type-safe environment variable, or nested variable?

For example in the case of the former, I think that solves by a type definition file support. (However, conventional dotenv has no concept of type safety.)

**Comment by mindhaq** [comment]
My use case is to put all dotenv properties into the build environment. Currently, I do it manually like this:

    environment.set("MARIADB_HOST", env.MARIADB_HOST.value)
    environment.set("MARIADB_PORT", env.MARIADB_PORT.value)
    ....

But I'd like to just do

    environment.putAll(env.allEntries)

**Comment by uzzu** [comment]
>environment.putAll(env.allEntries)

I could support to get all environment variables contains dotenv files provided, and it returns `Map<String, String>` though.
I'll try.

**Comment by uzzu** [comment]
Released at [1.1.0](https://github.com/uzzu/dotenv-gradle/blob/master/CHANGELOG.md#110---2020-04-21)

**Comment by mindhaq** [comment]
Thank you, I finally upgraded the plugin and `allVariables` works like a charm!

**Comment by ankit-jha** [comment]
@mindhaq Can you please share a usage snippet of your build.gradle ?

**Comment by mindhaq** [comment]
@ankit-jha 

From my `build.gradle.kts`:

```kotlin

fun readDotEnv(environment: MutableMap<String, Any>) {
    environment.putAll(env.allVariables)
}

tasks.getByName<BootRun>("bootRun") {
    readDotEnv(environment)
}

task<Test>("integrationTest") {
    readDotEnv(environment)
    // ....
}

```

This allows me to configure environment variables in a `.env` file.

**Comment by ankit-jha** [comment]
Thanks @mindhaq 

I ended up doing this in my build.gradle

```java
bootRun {
	File env_file = new File(".env")
	if(env_file.exists())
	{
		environment.putAll(env.allVariables)
	}
}
```

I still need to refactor this into a separate function so that other tasks can use it.
