### ISSUE TITLE
README is confusing wrt ENV_FILE

### ISSUE THREAD

**Issue by slhck** [uzzu/dotenv-gradle#44]
The readme mentions:

> If a .env.template file exists, this plugin refer it to create a environemnt variable properties in the env extension.

However, this appears not to work with the most recent version. Would it be possible to update the README to reflect the current behavior?

**Comment by uzzu** [comment]
@slhck 

What's a most recent version of Gradle? Is it 8.0 or any other versions?

Please try this https://github.com/uzzu/dotenv-gradle/tree/main/examples/basic then if you have any questions, Please reopen this issue and comment. 🙏

**Comment by slhck** [comment]
No, I meant your plugin's most recent version! It does not have that feature anymore but it is still mentioned in the documentation.

**Comment by slhck** [comment]
Or maybe I was mistaken, please ignore this issue for now. It appears the template function is still part of your plugin. When I posted this issue, it didn't work for me.

**Comment by uzzu** [comment]
@slhck 
Thanks for clarifying.
I recognized that README is difficult.
The pull requests for the README are welcome, so if you have any suggestions, please let me know.

**Comment by slhck** [comment]
I now know what the problem is:

The README says:

> Change a file to read instead of .env file.
>
> If environment variable ENV_FILE is set, The plugin read a file specified ENV_FILE instead of .env file.

It links to [an example](https://github.com/uzzu/dotenv-gradle/tree/main/examples/change_file), but there it says:

> Please use dotenv.filename in gradle.properties instead of ENV_FILE.

So it seems like `ENV_FILE` no longer works?

**Comment by mkatrenik** [comment]
@slhck  you can override gradle property through args
`./gradlew test -P dotenv.filename=.env.local`

**Comment by slhck** [comment]
@mkatrenik Yes, this is what it says in [the example](https://github.com/uzzu/dotenv-gradle/tree/main/examples/change_file#migrate-from-1x), and what I've quoted, but I wanted to point out that the readme is confusing and needs to be updated to not mention `ENV_FILE` if it doesn't work.
