### ISSUE TITLE
support providers.environmentVariable or System.getenv

### ISSUE THREAD

**Issue by xmlking** [uzzu/dotenv-gradle#47]
accessing variables via with `env.???` is good, but making those variable also accessible via `providers.environmentVariable("DB_FLYWAY_URL")` or  `System.getenv("GITHUB_TOKEN")`   make them work with scripts that already use them using Gradle's standard API

```
println(env.DB_FLYWAY_URL.isPresent)
println(env.DB_FLYWAY_URL.value)
```

```kotlin
flyway {
    cleanDisabled = false
    url = providers.environmentVariable("DB_FLYWAY_URL").orNull
    user = providers.environmentVariable("DB_USER").orNull 
    password = providers.environmentVariable("DB_PASSWORD").orNull
}

**Comment by uzzu** [comment]
Sounds good. I'll investigate that feature.

**Comment by uzzu** [comment]
I have investigated and it appears that overriding ProviderFactory on ServiceRegistry is not supported at this time.

https://discuss.gradle.org/t/plugin-service-registration/29342/4 

Sorry, but let this request be wontfix until that is possible.

Please reopen if my understanding is incorrect.
