### ISSUE TITLE
Variables defined in template do not have values returned

### ISSUE THREAD

**Issue by Nava2** [uzzu/dotenv-gradle#83]
**Describe the bug**
`.env.template`:

```bash
FOO=foo
BAR=bar
```

`.env`:

```bash
FOO=foo
```

Loaded entries:
```bash
{ 
  FOO: foo,
  BAR: null
}
```

**Expected behavior**

> If a .env.template file exists, this plugin populates environment variables from it, too. This means you can use the template to define the environment variables that are required for your project, and optionally override them in the .env file.

This reads like it will populate the _values_ from the environment, is the intention that it does not populate the values but only the var as `null`?

**Environment (please complete the following information):**
 - OS and OS version: macOS
 - Gradle Version: `8.7`
 - DotEnv Gradle Plugin Version: `4.0.0`

**Comment by uzzu** [comment]
The .env.template file is used by the plugin to provide default properties of “env” object, but does not resolve its values.
This plugin intended to be used as follows:
- Copy the .env.template to .env, Add .env to .gitignore
- Copy .env.template to a .env.dev file and specify dotenv.filename from gradle.properties.
  - [See the example](https://github.com/uzzu/dotenv-gradle/tree/66783a55d0abfab91f1953b6354338fddc9ab39a/examples/change_file)

**Comment by Nava2** [comment]
Thanks for the information, @uzzu. While I find this behaviour confusing, I see the intention. I updated the language in #84 to try and rectify my confusion on the behaviour. Let me know what you think! 

Of note: It'd be nice if it _did_ populate the values, though I expect that violates the "Twelve Step App" principles of dotenv.

**Comment by Nava2** [comment]
I failed to notice this same ask to populate the values from the `.env.template` was in #42.

**Comment by uzzu** [comment]
I don't intend to change this specification, but welcome the clarification of the document for more people. 👍
